version: '3.5'

services:
  postgresql:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgresql
    #    volumes:
    #      - ./pgdata:/var/lib/postgresql/data:Z
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1024MB'
    networks:
      - mynet

  redis:
    container_name: redis
    image: redis
    restart: always
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '512MB'
    networks:
      - mynet

  api1:
    image: api
    restart: always
    hostname: api1
    depends_on:
      - postgresql
      - redis
    expose:
      - 3000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '512MB'
    build:
      context: .
      dockerfile: dockerfile
    container_name: api-1
    networks:
      - mynet

  api2:
    image: api
    restart: always
    hostname: api2
    depends_on:
      - postgresql
      - redis
    expose:
      - 3000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '512MB'
    build:
      context: .
      dockerfile: dockerfile
    container_name: api-2
    networks:
      - mynet

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '512MB'
    networks:
      - mynet

volumes:
  redis:
    driver: local

networks:
  mynet:
    name: my-net